[tool.poetry]
name = "fraud-detection"
version = "0.1.0"
description = ""
authors = ["Filip Fija≈Çkowski <filip.fijalkowski@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
